### ISSUE TITLE
Pixel Vision 8.app not running on macOS Catalina

### ISSUE THREAD

**Issue by leissler** [PixelVision8/PixelVisionRunner#101]
Downloading and trying to open the "Pixel Vision 8.app" on a mac with Catalina will result in an error message "The application "Pixel Vision 8" can't be opened.".

To fix this, the following steps can be taken:
1. In a terminal go to the folder that contains the downloaded file "Pixel Vision 8.app"
2. From there change directory into "Pixel Vision 8.app/Contents/MacOS/"
3. chmod 755 Pixel\ Vision\ 8
4. In your finder you can now just double-click the "Pixel Vision 8.app" as usual. You will still have to allow executing this application from your security settings as usual for it to work.

**Comment by jessefreeman** [comment]
I need to try to fix this as part of the build script process.

**Comment by jessefreeman** [comment]
I've uploaded a new version with support for Catalina, you just need to manually approve the app in the security panel the first time you load it up.
