### ISSUE TITLE
Where are the files stored locally?

### ISSUE THREAD

**Issue by tsal** [PixelVision8/PixelVisionRunner#121]
The documentation keeps referring to my computer's `/Workspace` etc.. but doesn't once, in any sane way to find, spell out where that might be.

I found the local copy of the Trash bin, but that's it. I've tried creating new projects, but nothing can be found on my REAL computer's filesystem until I've dropped it in the trash bin.

I get this is free and all, but you'd think this would be the number 1 question asked by folks, and your documentation makes it difficult (so far, impossible) to find. I also couldn't find any issues so ...

**Comment by jessefreeman** [comment]
Have you had a chance to look at the section in the docs call "[Workspace](https://www.pixelvision8.com/courses/documentation/177667-using-pixel-vision-os/525553-the-workspace)"?

![image](https://user-images.githubusercontent.com/415666/78086521-3cbf3100-738c-11ea-8215-59e20d507011.png)
