### ISSUE TITLE
Weird Keyboard layout in the code editor

### ISSUE THREAD

**Issue by phedoff** [PixelVision8/PixelVisionRunner#122]
Using PV8 on a german qwertz-keyboard the keyboard layout is totally messed up, it's a mixture of a german and an english layout:

* characters and digits are mapped to correct keys, even "Y" and "Z" (mysterious - they are switched normally) and "+"
* the special characters ([shift][1..0]) are mapped to english layout, the next two keys do nothing (should print "-","+", "=")
* characters not available: "/", "[", "]","=", quotation marks  

So PV8 is currently unusable (at least the code editor).
Here are the different layouts: [US](https://de.wikipedia.org/wiki/Tastaturbelegung#USA) / [Germany](https://de.wikipedia.org/wiki/Tastaturbelegung#Deutschland_und_%C3%96sterreich) (german wikipedia - they have pictures of both).

Kind regards

**Comment by jessefreeman** [comment]
This has been fixed and will be included in the next release.
