### ISSUE TITLE
Sprite Editor - draw circle

### ISSUE THREAD

**Issue by AndyGFX** [PixelVision8/PixelVisionRunner#213]
Painted circle has problem with size. Is not painted in radius which is defined by mouse pointer. Max circle size is 6x6/7x7.

**Comment by jessefreeman** [comment]
Ned to clean up the logic for drawing the eclipse. Right now it's only calculating on odd pixels.

![image](https://user-images.githubusercontent.com/415666/80967170-ebb7b800-8de3-11ea-9008-1a270fb61542.png)

vs

![image](https://user-images.githubusercontent.com/415666/80967142-e195b980-8de3-11ea-9138-d6ac017560b7.png)
