### ISSUE TITLE
Documentation: Tables cropped

### ISSUE THREAD

**Issue by phedoff** [PixelVision8/PixelVisionRunner#240]
In the documentation the table explaining the bios settings values is cropped on the right hand side, cutting away half of the description.
file: "pv8 user guide.pdf"
pages: 84 - 90
![202004232723_072227](https://user-images.githubusercontent.com/33154602/80062100-3a876700-8533-11ea-9e08-f8ca7a25f993.png)

**Comment by jessefreeman** [comment]
Thanks for the heads up. I'm actually moving the docs to https://docs.pixelvision8.com/ and will be removing the PDF.

**Comment by phedoff** [comment]
Yeah, continued reading the manual online after finding this 'bug'. Btw: thanks for the keyboard fix. It's great to be able to use PV now.
