### ISSUE TITLE
Font editor background disappear

### ISSUE THREAD

**Issue by jessefreeman** [PixelVision8/PixelVisionRunner#241]
If you edit a character then leave and go back the background will not be set to the correct color.

![image](https://user-images.githubusercontent.com/415666/80544095-45505a80-897e-11ea-9eb8-8e61c5a6b649.png)

**Comment by rdominick** [comment]
I have this issue too; after it shows up, the draw cursor doesn't quite know what to do. You can end up drawing in the correct bg color, white, or the new light purple.
