### ISSUE TITLE
can not link to the demo 

### ISSUE THREAD

**Issue by KevinYeti** [PixelVision8/PixelVisionRunner#41]
Hi~
When I tried to click the links in the readme of the project, the link seems to be broken. 
They all lead to gitlab links but none of them exist. 
Did I miss something ?

**Comment by jessefreeman** [comment]
I need to update all the docs. I haven't updated them since the early build of PV8 so the links no longer work. I'll take care of this in the next release.

**Comment by hsandt** [comment]
Yeah, it seems all the links point to GitLab. I tried to enter the equivalent URL in GitHub, to no avail. There are even some wiki pages, but the GitHub Wiki link just redirects to the repository home.
